"""add phone

Revision ID: 145e7d0a62a8
Revises: 9a52dc56d644
Create Date: 2021-12-16 16:49:13.556909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145e7d0a62a8'
down_revision = '9a52dc56d644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
